connector.name=hive
hive.metastore.uri=thrift://hive-metastore:9083

# Configuración de conexión a MinIO
fs.native-s3.enabled=true
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=admin
hive.s3.aws-secret-key=password
hive.s3.path-style-access=true
hive.s3ssl.enabled=false

# Permisos para evitar errores al crear tablas externas
hive.allow-drop-table=true
hive.non-managed-table-writes-enabled=true