FROM apache/airflow:2.8.1

USER root
RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow

RUN pip install --no-cache-dir kafka-python pandas basketball-reference-web-scraper apache-airflow-providers-apache-spark pyspark==3.5.0 apache-airflow-providers-trino trino rapidfuzz